Repository AnthonyRentsch/AC297r_2019_somerville_parking, pull requests merged in 2019-10, with the labels that each got.

#5 Map parcels buildings 4
  notebooks/parcel_buildings_map.ipynb
  notebooks/parcel_map.ipynb
Labels: EDA

#13 closes #12
  labels/labels.csv
  labels/labels_full.csv
  notebooks/labelling-josh.ipynb
  notebooks/labelling_full.ipynb
  src/label.py
Labels: data

#15 closes #9
  labels/labels_full.csv
  notebooks/labelling_full.ipynb
Labels: data

#17 10 generator fun
  src/generator.py
Labels: model

#21 19 test model
  labels/labels.csv
  labels/labels_full.csv
  notebooks/initial_model.ipynb
  src/label.py
  src/training.py
Labels: model

#24 closes #23
  labels/labels_google_street_view.csv
  notebooks/labelling_street_view.ipynb
  src/label_google_street_view.py
Labels: data

#25 included model combining gsv and satellite imagery
  src/models.py
Labels: model
